//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheClueAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public game()
        {
            this.questions = new HashSet<question>();
        }
    
        public int id_game { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public int difficulty { get; set; }
        public double rating { get; set; }
        public byte[] picture { get; set; }
        public Nullable<int> duration { get; set; }
        public string description { get; set; }
        public int rating_counter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question> questions { get; set; }
    }
}
