//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheClueAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int id_question { get; set; }
        public Nullable<int> answer_type { get; set; }
        public string answer { get; set; }
        public string text_answer { get; set; }
        public double score { get; set; }
        public int game_id_game { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
    
        public virtual game game { get; set; }
    }
}
